/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.curvature;

import javax.swing.JProgressBar;
import javax.swing.JRadioButton;
import model.components.JImageView;
import org.jdesktop.swingx.JXImageView;

/**
 *
 * @author anderson
 */
public class ViewChainCode extends javax.swing.JFrame {

    /**
     * Creates new form ViewChainCode
     */
    public ViewChainCode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblImageCurvature = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        pgBar = new javax.swing.JProgressBar();
        ImageView = new JImageView();
        rbCoordinates = new javax.swing.JRadioButton();
        rbChainCode = new javax.swing.JRadioButton();
        rbHistChain = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Chain Code");

        lblImageCurvature.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnGenerate.setText("Generate Curvature");

        pgBar.setName(""); // NOI18N

        ImageView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout ImageViewLayout = new javax.swing.GroupLayout(ImageView);
        ImageView.setLayout(ImageViewLayout);
        ImageViewLayout.setHorizontalGroup(
            ImageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );
        ImageViewLayout.setVerticalGroup(
            ImageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        rbCoordinates.setText("Coordinates");

        rbChainCode.setText("Chain Code");

        rbHistChain.setText("Histograma Chain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ImageView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImageCurvature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbCoordinates)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbChainCode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbHistChain)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGenerate)
                            .addComponent(rbCoordinates)
                            .addComponent(rbChainCode)
                            .addComponent(rbHistChain))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImageCurvature, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                    .addComponent(pgBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImageView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXImageView ImageView;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImageCurvature;
    private javax.swing.JProgressBar pgBar;
    private javax.swing.JRadioButton rbChainCode;
    private javax.swing.JRadioButton rbCoordinates;
    private javax.swing.JRadioButton rbHistChain;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnGenerate() {
        return btnGenerate;
    }

    public void setBtnGenerate(javax.swing.JButton btnGenerate) {
        this.btnGenerate = btnGenerate;
    }

    public JImageView getImageView() {
        return (JImageView) ImageView;
    }

    public void setImageView(JImageView ImageView) {
        this.ImageView = ImageView;
    }
    

    public javax.swing.JLabel getLblImageCurvature() {
        return lblImageCurvature;
    }

    public void setLblImageCurvature(javax.swing.JLabel lblImageCurvature) {
        this.lblImageCurvature = lblImageCurvature;
    }

    public JProgressBar getPgBar() {
        return pgBar;
    }

    public void setPgBar(JProgressBar pgBar) {
        this.pgBar = pgBar;
    }

    public JRadioButton getRbChainCode() {
        return rbChainCode;
    }

    public void setRbChainCode(JRadioButton rbChainCode) {
        this.rbChainCode = rbChainCode;
    }

    public JRadioButton getRbCoordinates() {
        return rbCoordinates;
    }

    public void setRbCoordinates(JRadioButton rbCoordinates) {
        this.rbCoordinates = rbCoordinates;
    }

    public JRadioButton getRbHistChain() {
        return rbHistChain;
    }

    public void setRbHistChain(JRadioButton rbHistChain) {
        this.rbHistChain = rbHistChain;
    }
}
