/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.recognition;

import javax.swing.JProgressBar;
import javax.swing.JTextField;

/**
 *
 * @author anderson
 */
public class ViewSimileImage extends javax.swing.JFrame {

    /**
     * Creates new form ViewSimileImage
     */
    public ViewSimileImage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompImage = new javax.swing.JLabel();
        btnOpen1 = new javax.swing.JButton();
        btnOpen2 = new javax.swing.JButton();
        jxImage1 = new model.components.JImageView();
        jxImage2 = new model.components.JImageView();
        btnStart = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        lblDstEuclidean = new javax.swing.JLabel();
        txtDstResult = new javax.swing.JLabel();
        jxGrafico = new model.components.JImageView();
        pgBar = new javax.swing.JProgressBar();
        lblFourier = new javax.swing.JLabel();
        txtSeries = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAngle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCompImage.setText("Comparision Image");

        btnOpen1.setText("Open image 1");

        btnOpen2.setText("Open image 2");

        jxImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jxImage1Layout = new javax.swing.GroupLayout(jxImage1);
        jxImage1.setLayout(jxImage1Layout);
        jxImage1Layout.setHorizontalGroup(
            jxImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jxImage1Layout.setVerticalGroup(
            jxImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jxImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jxImage2Layout = new javax.swing.GroupLayout(jxImage2);
        jxImage2.setLayout(jxImage2Layout);
        jxImage2Layout.setHorizontalGroup(
            jxImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jxImage2Layout.setVerticalGroup(
            jxImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        btnStart.setText("Start");

        lblResult.setText("Result:");

        lblDstEuclidean.setText("Distance euclidean:");

        txtDstResult.setText("0");

        jxGrafico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jxGraficoLayout = new javax.swing.GroupLayout(jxGrafico);
        jxGrafico.setLayout(jxGraficoLayout);
        jxGraficoLayout.setHorizontalGroup(
            jxGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jxGraficoLayout.setVerticalGroup(
            jxGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblFourier.setText("Fourier Series");

        txtSeries.setText("6");

        jLabel1.setText("Angle");

        txtAngle.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jxImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOpen1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(lblCompImage))
                                .addGap(15, 15, 15)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOpen2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jxImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jxGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResult)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDstEuclidean)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDstResult, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAngle))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFourier)
                            .addComponent(txtSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOpen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResult)
                            .addComponent(lblFourier)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jxImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jxImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnStart)
                                .addGap(2, 2, 2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDstEuclidean)
                                    .addComponent(txtDstResult)
                                    .addComponent(txtAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(jxGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(pgBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen1;
    private javax.swing.JButton btnOpen2;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.JXImageView jxGrafico;
    private org.jdesktop.swingx.JXImageView jxImage1;
    private org.jdesktop.swingx.JXImageView jxImage2;
    private javax.swing.JLabel lblCompImage;
    private javax.swing.JLabel lblDstEuclidean;
    private javax.swing.JLabel lblFourier;
    private javax.swing.JLabel lblResult;
    private javax.swing.JProgressBar pgBar;
    private javax.swing.JTextField txtAngle;
    private javax.swing.JLabel txtDstResult;
    private javax.swing.JTextField txtSeries;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnOpen1() {
        return btnOpen1;
    }

    public void setBtnOpen1(javax.swing.JButton btnOpen1) {
        this.btnOpen1 = btnOpen1;
    }

    public javax.swing.JButton getBtnOpen2() {
        return btnOpen2;
    }

    public void setBtnOpen2(javax.swing.JButton btnOpen2) {
        this.btnOpen2 = btnOpen2;
    }

    public javax.swing.JButton getBtnStart() {
        return btnStart;
    }

    public void setBtnStart(javax.swing.JButton btnStart) {
        this.btnStart = btnStart;
    }

    public org.jdesktop.swingx.JXImageView getJxGrafico() {
        return jxGrafico;
    }

    public void setJxGrafico(org.jdesktop.swingx.JXImageView jxGrafico) {
        this.jxGrafico = jxGrafico;
    }

    public org.jdesktop.swingx.JXImageView getJxImage1() {
        return jxImage1;
    }

    public void setJxImage1(org.jdesktop.swingx.JXImageView jxImage1) {
        this.jxImage1 = jxImage1;
    }

    public org.jdesktop.swingx.JXImageView getJxImage2() {
        return jxImage2;
    }

    public void setJxImage2(org.jdesktop.swingx.JXImageView jxImage2) {
        this.jxImage2 = jxImage2;
    }

    public javax.swing.JLabel getTxtDstResult() {
        return txtDstResult;
    }

    public void setTxtDstResult(javax.swing.JLabel txtDstResult) {
        this.txtDstResult = txtDstResult;
    }

    public JProgressBar getPgBar() {
        return pgBar;
    }

    public void setPgBar(JProgressBar pgBar) {
        this.pgBar = pgBar;
    }

    public JTextField getTxtSeries() {
        return txtSeries;
    }

    public void setTxtSeries(JTextField txtSeries) {
        this.txtSeries = txtSeries;
    }

    public JTextField getTxtAngle() {
        return txtAngle;
    }

    public void setTxtAngle(JTextField txtAngle) {
        this.txtAngle = txtAngle;
    }
    
}
