/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FilenameFilter;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;
import model.Grafico;
import model.Histograma;

/**
 *
 * @author Anderson
 */
public class ViewPadrao extends javax.swing.JFrame {

    /**
     * Creates new form ViewPadrao
     */
    public ViewPadrao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbabrir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jllista = new javax.swing.JList();
        jbagrupar = new javax.swing.JButton();
        jldados = new javax.swing.JLabel();
        jbabrirbanco = new javax.swing.JButton();
        jbcriar = new javax.swing.JButton();
        jbclassificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(620, 480));
        setPreferredSize(new java.awt.Dimension(620, 480));

        jbabrir.setText("Localizar diretório de imagens");
        jbabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbabrirActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jllista);

        jbagrupar.setText("Agrupar Espécies");
        jbagrupar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbagruparActionPerformed(evt);
            }
        });

        jldados.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jldados.setText("Padrão:");

        jbabrirbanco.setText("Localizar Banco de Imagens");
        jbabrirbanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbabrirbancoActionPerformed(evt);
            }
        });

        jbcriar.setText("Criar Padrão");
        jbcriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcriarActionPerformed(evt);
            }
        });

        jbclassificar.setText("Classificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jldados)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbabrir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbabrirbanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbcriar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbagrupar)
                            .addComponent(jbclassificar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(264, 264, 264))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jldados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbabrirbanco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 74, Short.MAX_VALUE)
                        .addComponent(jbagrupar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jbcriar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jbclassificar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbabrirActionPerformed

    }//GEN-LAST:event_jbabrirActionPerformed

    private void jbagruparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbagruparActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbagruparActionPerformed

    private void jbabrirbancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbabrirbancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbabrirbancoActionPerformed

    private void jbcriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcriarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbcriarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbabrir;
    private javax.swing.JButton jbabrirbanco;
    private javax.swing.JButton jbagrupar;
    private javax.swing.JButton jbclassificar;
    private javax.swing.JButton jbcriar;
    private javax.swing.JLabel jldados;
    private javax.swing.JList jllista;
    // End of variables declaration//GEN-END:variables

    public JButton getJbclassificar() {
        return jbclassificar;
    }

    public void setJbclassificar(JButton jbclassificar) {
        this.jbclassificar = jbclassificar;
    }
    
    public JButton getJbabrir() {
        return jbabrir;
    }

    public void setJbabrir(JButton jbabrir) {
        this.jbabrir = jbabrir;
    }

    public JButton getJbabrirbanco() {
        return jbabrirbanco;
    }

    public void setJbabrirbanco(JButton jbabrirbanco) {
        this.jbabrirbanco = jbabrirbanco;
    }

    public JButton getJbagrupar() {
        return jbagrupar;
    }

    public void setJbagrupar(JButton jbagrupar) {
        this.jbagrupar = jbagrupar;
    }

    public JButton getJbcriar() {
        return jbcriar;
    }

    public void setJbcriar(JButton jbcriar) {
        this.jbcriar = jbcriar;
    }

    public JLabel getJldados() {
        return jldados;
    }

    public void setJldados(JLabel jldados) {
        this.jldados = jldados;
    }

    public JList getJllista() {
        return jllista;
    }

    public void setJllista(JList jllista) {
        this.jllista = jllista;
    }

}
