/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author anderson
 */
public class viewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form viewPrincipal
     */
    public viewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        mFilters = new javax.swing.JMenu();
        mFilterBlur = new javax.swing.JMenu();
        mFilterBlurLow = new javax.swing.JMenuItem();
        mFilterBlurMedian = new javax.swing.JMenuItem();
        mSegmenting = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mFilterEdgeSobel = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mDescriptors = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mCurvatureChainCode = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mRecognition = new javax.swing.JMenu();
        mRecognitionGroup = new javax.swing.JMenuItem();
        mPatternGeneration = new javax.swing.JMenuItem();
        mComparisionImage = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mFile.setText("File");

        menuOpen.setText("Open");
        mFile.add(menuOpen);

        jMenuBar1.add(mFile);

        mFilters.setText("Filters");

        mFilterBlur.setText("Blur");

        mFilterBlurLow.setText("Low-Pass ");
        mFilterBlurLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFilterBlurLowActionPerformed(evt);
            }
        });
        mFilterBlur.add(mFilterBlurLow);

        mFilterBlurMedian.setText("Median");
        mFilterBlur.add(mFilterBlurMedian);

        mFilters.add(mFilterBlur);

        jMenuBar1.add(mFilters);

        mSegmenting.setText("Segmenting");

        jMenu2.setText("Edge - Detect");

        mFilterEdgeSobel.setText("Sobel");
        jMenu2.add(mFilterEdgeSobel);

        jMenuItem5.setText("Prewitt");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Roberts");
        jMenu2.add(jMenuItem6);

        mSegmenting.add(jMenu2);

        jMenu1.setText("Thresholding");

        jMenuItem3.setText("Otsu");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Max. Entropia");
        jMenu1.add(jMenuItem4);

        mSegmenting.add(jMenu1);

        jMenuBar1.add(mSegmenting);

        mDescriptors.setText("Descriptors");

        jMenuItem1.setText("Signature");
        mDescriptors.add(jMenuItem1);

        mCurvatureChainCode.setText("Chain Code");
        mDescriptors.add(mCurvatureChainCode);

        jMenuItem2.setText("Fourier");
        mDescriptors.add(jMenuItem2);

        jMenuBar1.add(mDescriptors);

        mRecognition.setText("Recognition");

        mRecognitionGroup.setText("Species Group");
        mRecognition.add(mRecognitionGroup);

        mPatternGeneration.setText("Pattern Generation");
        mRecognition.add(mPatternGeneration);

        mComparisionImage.setText("Comparison of two images");
        mComparisionImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mComparisionImageActionPerformed(evt);
            }
        });
        mRecognition.add(mComparisionImage);

        jMenuBar1.add(mRecognition);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mFilterBlurLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFilterBlurLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mFilterBlurLowActionPerformed

    private void mComparisionImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mComparisionImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mComparisionImageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JDesktopPane jPanelPrincipal;
    private javax.swing.JMenuItem mComparisionImage;
    private javax.swing.JMenuItem mCurvatureChainCode;
    private javax.swing.JMenu mDescriptors;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mFilterBlur;
    private javax.swing.JMenuItem mFilterBlurLow;
    private javax.swing.JMenuItem mFilterBlurMedian;
    private javax.swing.JMenuItem mFilterEdgeSobel;
    private javax.swing.JMenu mFilters;
    private javax.swing.JMenuItem mPatternGeneration;
    private javax.swing.JMenu mRecognition;
    private javax.swing.JMenuItem mRecognitionGroup;
    private javax.swing.JMenu mSegmenting;
    private javax.swing.JMenuItem menuOpen;
    // End of variables declaration//GEN-END:variables
    
    
    //getters e setters
    public JDesktopPane getjPanelPrincipal() {
        return jPanelPrincipal;
    }

    public void setjPanelPrincipal(JDesktopPane jPanelPrincipal) {
        this.jPanelPrincipal = jPanelPrincipal;
    }

    public javax.swing.JMenuItem getMenuOpen() {
        return menuOpen;
    }
    
    public void setMenuOpen(javax.swing.JMenuItem menuOpen) {
        this.menuOpen = menuOpen;
    }

    public JMenu getmCurvature() {
        return mDescriptors;
    }

    public void setmCurvature(JMenu mCurvature) {
        this.mDescriptors = mCurvature;
    }

    public JMenu getmFile() {
        return mFile;
    }

    public void setmFile(JMenu mFile) {
        this.mFile = mFile;
    }

    public JMenu getmFilters() {
        return mFilters;
    }

    public void setmFilters(JMenu mFilters) {
        this.mFilters = mFilters;
    }

    public JMenuItem getmFilterBlurLow() {
        return mFilterBlurLow;
    }

    public void setmFilterBlurLow(JMenuItem mFilterBlurLow) {
        this.mFilterBlurLow = mFilterBlurLow;
    }

    public JMenuItem getmFilterBlurMedian() {
        return mFilterBlurMedian;
    }

    public void setmFilterBlurMedian(JMenuItem mFilterBlurMedian) {
        this.mFilterBlurMedian = mFilterBlurMedian;
    }

    public JMenuItem getmFilterEdgeSobel() {
        return mFilterEdgeSobel;
    }

    public void setmFilterEdgeSobel(JMenuItem mFilterEdgeSobel) {
        this.mFilterEdgeSobel = mFilterEdgeSobel;
    }

    public JMenuItem getmCurvatureChainCode() {
        return mCurvatureChainCode;
    }

    public void setmCurvatureChainCode(JMenuItem mCurvatureChainCode) {
        this.mCurvatureChainCode = mCurvatureChainCode;
    }

    public JMenuItem getmRecognitionGroup() {
        return mRecognitionGroup;
    }

    public void setmRecognitionGroup(JMenuItem mRecognitionGroup) {
        this.mRecognitionGroup = mRecognitionGroup;
    }

    public JMenuItem getmRecognitionPattern() {
        return mPatternGeneration;
    }

    public void setmRecognitionPattern(JMenuItem mRecognitionPattern) {
        this.mPatternGeneration = mRecognitionPattern;
    }

    public JMenuItem getmSimileImage() {
        return mComparisionImage;
    }

    public void setmSimileImage(JMenuItem mSimileImage) {
        this.mComparisionImage = mSimileImage;
    }
    
}
