/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author Anderson
 */
public class ViewClassificar extends javax.swing.JFrame {

    /**
     * Creates new form ViewClassificar
     */
    public ViewClassificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbabrir = new javax.swing.JButton();
        jbclassificar = new javax.swing.JButton();
        jlImage = new javax.swing.JLabel();
        jlhisimage = new javax.swing.JLabel();
        jbselecionar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlImageE = new javax.swing.JLabel();
        jlespecie = new javax.swing.JLabel();
        jldiferenca = new javax.swing.JLabel();
        jlhistogramamedio = new javax.swing.JLabel();
        jlhistogramapadrao = new javax.swing.JLabel();
        jlespecienome = new javax.swing.JLabel();
        jLdmred = new javax.swing.JLabel();
        jLdmgreen = new javax.swing.JLabel();
        jbhdesvio = new javax.swing.JButton();
        jbhmedio = new javax.swing.JButton();
        jlhistograma = new javax.swing.JLabel();
        jlhisimageE = new javax.swing.JLabel();
        jLdmblue = new javax.swing.JLabel();
        jLddpblue = new javax.swing.JLabel();
        jLddpgreen = new javax.swing.JLabel();
        jLddpred = new javax.swing.JLabel();

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 600));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(710, 780));
        setResizable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(255, 0, 102));

        jbabrir.setText("Abrir Imagem");
        jbabrir.setOpaque(false);
        jbabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbabrirActionPerformed(evt);
            }
        });

        jbclassificar.setText("Classificar");

        jlImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlhisimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbselecionar.setText("Abrir Espécie");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlImage, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlhisimage, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbselecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbclassificar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbselecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbclassificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlImage, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlhisimage, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlImageE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlespecie.setText("Espécie:");

        jldiferenca.setText("Diferenças:");

        jlhistogramamedio.setText("Histograma Medio:");

        jlhistogramapadrao.setText("Histograma Desvio Padrão:");

        jlespecienome.setText("---");

        jLdmred.setForeground(new java.awt.Color(255, 0, 0));
        jLdmred.setText("---");

        jLdmgreen.setForeground(new java.awt.Color(0, 153, 0));
        jLdmgreen.setText("---");

        jbhdesvio.setText("Desvio Padrão");

        jbhmedio.setText("Médio");

        jlhistograma.setText("Histograma:");

        jlhisimageE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLdmblue.setForeground(new java.awt.Color(0, 0, 255));
        jLdmblue.setText("---");

        jLddpblue.setForeground(new java.awt.Color(0, 0, 255));
        jLddpblue.setText("---");

        jLddpgreen.setForeground(new java.awt.Color(0, 153, 0));
        jLddpgreen.setText("---");

        jLddpred.setForeground(new java.awt.Color(255, 0, 0));
        jLddpred.setText("---");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlespecie)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlespecienome))
                    .addComponent(jlImageE, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlhisimageE, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jldiferenca)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlhistogramamedio)
                                .addGap(47, 47, 47)
                                .addComponent(jLdmred)
                                .addGap(18, 18, 18)
                                .addComponent(jLdmgreen)
                                .addGap(18, 18, 18)
                                .addComponent(jLdmblue))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlhistogramapadrao)
                                .addGap(37, 37, 37)
                                .addComponent(jLddpred)
                                .addGap(18, 18, 18)
                                .addComponent(jLddpgreen)
                                .addGap(18, 18, 18)
                                .addComponent(jLddpblue))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlhistograma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbhmedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbhdesvio)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlespecie)
                    .addComponent(jldiferenca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlhistogramamedio)
                    .addComponent(jlespecienome)
                    .addComponent(jLdmred)
                    .addComponent(jLdmblue)
                    .addComponent(jLdmgreen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLddpred)
                        .addComponent(jLddpblue)
                        .addComponent(jLddpgreen))
                    .addComponent(jlhistogramapadrao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbhdesvio)
                    .addComponent(jbhmedio)
                    .addComponent(jlhistograma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlImageE, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlhisimageE, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbabrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbabrirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLddpblue;
    private javax.swing.JLabel jLddpgreen;
    private javax.swing.JLabel jLddpred;
    private javax.swing.JLabel jLdmblue;
    private javax.swing.JLabel jLdmgreen;
    private javax.swing.JLabel jLdmred;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbabrir;
    private javax.swing.JButton jbclassificar;
    private javax.swing.JButton jbhdesvio;
    private javax.swing.JButton jbhmedio;
    private javax.swing.JButton jbselecionar;
    private javax.swing.JLabel jlImage;
    private javax.swing.JLabel jlImageE;
    private javax.swing.JLabel jldiferenca;
    private javax.swing.JLabel jlespecie;
    private javax.swing.JLabel jlespecienome;
    private javax.swing.JLabel jlhisimage;
    private javax.swing.JLabel jlhisimageE;
    private javax.swing.JLabel jlhistograma;
    private javax.swing.JLabel jlhistogramamedio;
    private javax.swing.JLabel jlhistogramapadrao;
    // End of variables declaration//GEN-END:variables

    public JButton getJbabrir() {
        return jbabrir;
    }

    public void setJbabrir(JButton jbabrir) {
        this.jbabrir = jbabrir;
    }

    public JButton getJbclassificar() {
        return jbclassificar;
    }

    public void setJbclassificar(JButton jbclassificar) {
        this.jbclassificar = jbclassificar;
    }

    public JButton getJbhdesvio() {
        return jbhdesvio;
    }

    public void setJbhdesvio(JButton jbhdesvio) {
        this.jbhdesvio = jbhdesvio;
    }

    public JButton getJbhmedio() {
        return jbhmedio;
    }

    public void setJbhmedio(JButton jbhmedio) {
        this.jbhmedio = jbhmedio;
    }

    public JLabel getJlImage() {
        return jlImage;
    }

    public void setJlImage(JLabel jlImage) {
        this.jlImage = jlImage;
    }

    public JLabel getJlImageE() {
        return jlImageE;
    }

    public void setJlImageE(JLabel jlImageE) {
        this.jlImageE = jlImageE;
    }

    public JLabel getJlespecienome() {
        return jlespecienome;
    }

    public void setJlespecienome(JLabel jlespecienome) {
        this.jlespecienome = jlespecienome;
    }

    public JLabel getJlhisimage() {
        return jlhisimage;
    }

    public void setJlhisimage(JLabel jlhisimage) {
        this.jlhisimage = jlhisimage;
    }

    public JLabel getJlhisimageE() {
        return jlhisimageE;
    }

    public void setJlhisimageE(JLabel jlhisimageE) {
        this.jlhisimageE = jlhisimageE;
    }

    public JLabel getjLddpblue() {
        return jLddpblue;
    }

    public void setjLddpblue(JLabel jLddpblue) {
        this.jLddpblue = jLddpblue;
    }

    public JLabel getjLddpgreen() {
        return jLddpgreen;
    }

    public void setjLddpgreen(JLabel jLddpgreen) {
        this.jLddpgreen = jLddpgreen;
    }

    public JLabel getjLddpred() {
        return jLddpred;
    }

    public void setjLddpred(JLabel jLddpred) {
        this.jLddpred = jLddpred;
    }

    public JLabel getjLdmblue() {
        return jLdmblue;
    }

    public void setjLdmblue(JLabel jLdmblue) {
        this.jLdmblue = jLdmblue;
    }

    public JLabel getjLdmgreen() {
        return jLdmgreen;
    }

    public void setjLdmgreen(JLabel jLdmgreen) {
        this.jLdmgreen = jLdmgreen;
    }

    public JLabel getjLdmred() {
        return jLdmred;
    }

    public void setjLdmred(JLabel jLdmred) {
        this.jLdmred = jLdmred;
    }

    public JButton getJbselecionar() {
        return jbselecionar;
    }

    public void setJbselecionar(JButton jbselecionar) {
        this.jbselecionar = jbselecionar;
    }
}
