/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Anderson
 */
public class ViewPadrao extends javax.swing.JFrame {

    /**
     * Creates new form ViewPadrao
     */
    public ViewPadrao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jldados = new javax.swing.JLabel();
        jbabrirbanco = new javax.swing.JButton();
        jbagrupar = new javax.swing.JButton();
        jbclassificar = new javax.swing.JButton();
        jbcriar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rbnot = new javax.swing.JRadioButton();
        rbtwosurf = new javax.swing.JRadioButton();
        rbfoursurf = new javax.swing.JRadioButton();
        rbyest = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtnomepadrao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblcaminho = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbeuclidiana = new javax.swing.JRadioButton();
        rbmanhattan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rbsup = new javax.swing.JRadioButton();
        rbinf = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setResizable(false);

        jldados.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jldados.setText("Padrão:");

        jbabrirbanco.setText("Localizar Banco de Imagens");
        jbabrirbanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbabrirbancoActionPerformed(evt);
            }
        });

        jbagrupar.setText("Agrupar Espécies");
        jbagrupar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbagruparActionPerformed(evt);
            }
        });

        jbclassificar.setText("Classificar");

        jbcriar.setText("Criar Padrão");
        jbcriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcriarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rbnot.setText("NO_THRESHOLD");

        rbtwosurf.setText("TWO SURFACE");

        rbfoursurf.setText("FOUR SURFACE");

        rbyest.setText("THRESHOLD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbnot)
                    .addComponent(rbtwosurf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbfoursurf)
                    .addComponent(rbyest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnot)
                    .addComponent(rbyest))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbfoursurf)
                    .addComponent(rbtwosurf))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel1.setText("Nome do diretoro:");

        jLabel2.setText("Caminho do banco:");

        jLabel3.setText("Tipo de extraçao:");

        jLabel4.setText("Calculo de distancia:");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rbeuclidiana.setText("Euclidiana");

        rbmanhattan.setText("Manhattan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbeuclidiana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbmanhattan)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbeuclidiana)
                    .addComponent(rbmanhattan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Superficie:");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rbsup.setText("Superior");

        rbinf.setText("Inferior");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbsup)
                    .addComponent(rbinf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbsup)
                .addGap(18, 18, 18)
                .addComponent(rbinf)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcaminho, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtnomepadrao)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jldados)
                                .addComponent(jbabrirbanco, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addComponent(jbagrupar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbcriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbclassificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jldados)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbabrirbanco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcaminho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtnomepadrao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jbagrupar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbcriar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbclassificar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbagruparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbagruparActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbagruparActionPerformed

    private void jbabrirbancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbabrirbancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbabrirbancoActionPerformed

    private void jbcriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcriarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbcriarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbabrirbanco;
    private javax.swing.JButton jbagrupar;
    private javax.swing.JButton jbclassificar;
    private javax.swing.JButton jbcriar;
    private javax.swing.JLabel jldados;
    private javax.swing.JLabel lblcaminho;
    private javax.swing.JRadioButton rbeuclidiana;
    private javax.swing.JRadioButton rbfoursurf;
    private javax.swing.JRadioButton rbinf;
    private javax.swing.JRadioButton rbmanhattan;
    private javax.swing.JRadioButton rbnot;
    private javax.swing.JRadioButton rbsup;
    private javax.swing.JRadioButton rbtwosurf;
    private javax.swing.JRadioButton rbyest;
    private javax.swing.JTextField txtnomepadrao;
    // End of variables declaration//GEN-END:variables

    public JButton getJbclassificar() {
        return jbclassificar;
    }

    public void setJbclassificar(JButton jbclassificar) {
        this.jbclassificar = jbclassificar;
    }

    public JButton getJbabrirbanco() {
        return jbabrirbanco;
    }

    public void setJbabrirbanco(JButton jbabrirbanco) {
        this.jbabrirbanco = jbabrirbanco;
    }

    public JButton getJbagrupar() {
        return jbagrupar;
    }

    public void setJbagrupar(JButton jbagrupar) {
        this.jbagrupar = jbagrupar;
    }

    public JButton getJbcriar() {
        return jbcriar;
    }

    public void setJbcriar(JButton jbcriar) {
        this.jbcriar = jbcriar;
    }

    public JLabel getJldados() {
        return jldados;
    }

    public void setJldados(JLabel jldados) {
        this.jldados = jldados;
    }

    public JRadioButton getRbfoursurf() {
        return rbfoursurf;
    }

    public void setRbfoursurf(JRadioButton rbfoursurf) {
        this.rbfoursurf = rbfoursurf;
    }

    public JRadioButton getRbnot() {
        return rbnot;
    }

    public void setRbnot(JRadioButton rbnot) {
        this.rbnot = rbnot;
    }

    public JRadioButton getRbtwosurf() {
        return rbtwosurf;
    }

    public void setRbtwosurf(JRadioButton rbtwosurf) {
        this.rbtwosurf = rbtwosurf;
    }

    public JRadioButton getRbyest() {
        return rbyest;
    }

    public void setRbyest(JRadioButton rbyest) {
        this.rbyest = rbyest;
    }

    public JLabel getLblcaminho() {
        return lblcaminho;
    }

    public void setLblcaminho(JLabel lblcaminho) {
        this.lblcaminho = lblcaminho;
    }

    public JTextField getTxtnomepadrao() {
        return txtnomepadrao;
    }

    public void setTxtnomepadrao(JTextField txtnomepadrao) {
        this.txtnomepadrao = txtnomepadrao;
    }

    public JRadioButton getRbeuclidiana() {
        return rbeuclidiana;
    }

    public void setRbeuclidiana(JRadioButton rbeuclidiana) {
        this.rbeuclidiana = rbeuclidiana;
    }

    public JRadioButton getRbmanhattan() {
        return rbmanhattan;
    }

    public void setRbmanhattan(JRadioButton rbmanhattan) {
        this.rbmanhattan = rbmanhattan;
    }

    public JRadioButton getRbinf() {
        return rbinf;
    }

    public void setRbinf(JRadioButton rbinf) {
        this.rbinf = rbinf;
    }

    public JRadioButton getRbsup() {
        return rbsup;
    }

    public void setRbsup(JRadioButton rbsup) {
        this.rbsup = rbsup;
    }

}
