/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControlPDI;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FilenameFilter;
import javax.imageio.IIOImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.StyledEditorKit;
import model.Grafico;

/**
 *
 * @author Anderson
 */
public class ViewPDI extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal2
     */
    public ViewPDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlImage = new javax.swing.JLabel();
        jbexecutar = new javax.swing.JButton();
        jpopcoes = new javax.swing.JPanel();
        jpsuavizacao = new javax.swing.JPanel();
        jlsuavizacao = new javax.swing.JLabel();
        jrpassabaixas = new javax.swing.JRadioButton();
        jrmediana = new javax.swing.JRadioButton();
        jsmascara = new javax.swing.JSlider();
        jltammask = new javax.swing.JLabel();
        jpequalizacao = new javax.swing.JPanel();
        jlequalizacao = new javax.swing.JLabel();
        jrequalizargb = new javax.swing.JRadioButton();
        jlopcoes = new javax.swing.JLabel();
        jpsegmentacao = new javax.swing.JPanel();
        jlsegmentacao = new javax.swing.JLabel();
        jrsobel = new javax.swing.JRadioButton();
        jrprewitt = new javax.swing.JRadioButton();
        jrroberts = new javax.swing.JRadioButton();
        jplimiarizacao = new javax.swing.JPanel();
        jllimiarizacao = new javax.swing.JLabel();
        jrmaxentropia = new javax.swing.JRadioButton();
        jlpadraolimiar = new javax.swing.JLabel();
        jllimiarutilizado = new javax.swing.JLabel();
        jllimiar = new javax.swing.JLabel();
        jbsalvar = new javax.swing.JButton();
        jmPrincipal = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmiAbrir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(669, 680));
        setResizable(false);

        jlImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlImage.setLabelFor(jlImage);
        jlImage.setAutoscrolls(true);
        jlImage.setToolTipText("");
        jlImage.setAutoscrolls(true);
        jlImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbexecutar.setText("Executar");
        jbexecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexecutarActionPerformed(evt);
            }
        });

        jpopcoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpsuavizacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlsuavizacao.setText("Suavização");

        jrpassabaixas.setText("Filtro de Passa - Baixas");

        jrmediana.setText("Filtro de mediana");

        jsmascara.setMajorTickSpacing(2);
        jsmascara.setMaximum(15);
        jsmascara.setMinimum(3);
        jsmascara.setMinorTickSpacing(2);
        jsmascara.setPaintLabels(true);
        jsmascara.setPaintTicks(true);
        jsmascara.setSnapToTicks(true);
        jsmascara.setValue(3);
        jsmascara.setValueIsAdjusting(true);
        jsmascara.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsmascaraStateChanged(evt);
            }
        });

        jltammask.setText("Tamanho da Máscara");

        javax.swing.GroupLayout jpsuavizacaoLayout = new javax.swing.GroupLayout(jpsuavizacao);
        jpsuavizacao.setLayout(jpsuavizacaoLayout);
        jpsuavizacaoLayout.setHorizontalGroup(
            jpsuavizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsuavizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpsuavizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsmascara, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addGroup(jpsuavizacaoLayout.createSequentialGroup()
                        .addGroup(jpsuavizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrmediana)
                            .addComponent(jrpassabaixas)
                            .addComponent(jlsuavizacao)
                            .addComponent(jltammask))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpsuavizacaoLayout.setVerticalGroup(
            jpsuavizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsuavizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlsuavizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrpassabaixas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrmediana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jltammask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jsmascara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpequalizacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlequalizacao.setText("Equalização");

        jrequalizargb.setText("Equalização  (RGB)");

        javax.swing.GroupLayout jpequalizacaoLayout = new javax.swing.GroupLayout(jpequalizacao);
        jpequalizacao.setLayout(jpequalizacaoLayout);
        jpequalizacaoLayout.setHorizontalGroup(
            jpequalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpequalizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpequalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrequalizargb)
                    .addComponent(jlequalizacao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpequalizacaoLayout.setVerticalGroup(
            jpequalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpequalizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlequalizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrequalizargb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlopcoes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlopcoes.setText("Opções");

        jpsegmentacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlsegmentacao.setText("Segmentação");

        jrsobel.setText("Operador de Sobel");

        jrprewitt.setText("Operador de Prewitt");

        jrroberts.setText("Operador de Roberts");

        javax.swing.GroupLayout jpsegmentacaoLayout = new javax.swing.GroupLayout(jpsegmentacao);
        jpsegmentacao.setLayout(jpsegmentacaoLayout);
        jpsegmentacaoLayout.setHorizontalGroup(
            jpsegmentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsegmentacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpsegmentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrroberts)
                    .addComponent(jrprewitt)
                    .addComponent(jrsobel)
                    .addComponent(jlsegmentacao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpsegmentacaoLayout.setVerticalGroup(
            jpsegmentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsegmentacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlsegmentacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrsobel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrprewitt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrroberts)
                .addContainerGap())
        );

        jplimiarizacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jllimiarizacao.setText("Limiarização");

        jrmaxentropia.setText("Max Entrópia (Limiar automatico)");

        jlpadraolimiar.setText("Valor padrão: 32");

        jllimiarutilizado.setText("Valor Utilizado: ");

        jllimiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jplimiarizacaoLayout = new javax.swing.GroupLayout(jplimiarizacao);
        jplimiarizacao.setLayout(jplimiarizacaoLayout);
        jplimiarizacaoLayout.setHorizontalGroup(
            jplimiarizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplimiarizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplimiarizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrmaxentropia)
                    .addComponent(jllimiarizacao)
                    .addGroup(jplimiarizacaoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jplimiarizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplimiarizacaoLayout.createSequentialGroup()
                                .addComponent(jllimiarutilizado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jllimiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlpadraolimiar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplimiarizacaoLayout.setVerticalGroup(
            jplimiarizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplimiarizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jllimiarizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrmaxentropia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpadraolimiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jplimiarizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jllimiarutilizado)
                    .addComponent(jllimiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpopcoesLayout = new javax.swing.GroupLayout(jpopcoes);
        jpopcoes.setLayout(jpopcoesLayout);
        jpopcoesLayout.setHorizontalGroup(
            jpopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpopcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpsegmentacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpequalizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpsuavizacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpopcoesLayout.createSequentialGroup()
                        .addComponent(jlopcoes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jplimiarizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpopcoesLayout.setVerticalGroup(
            jpopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpopcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlopcoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpsuavizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpequalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpsegmentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jplimiarizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbsalvar.setText("Salvar");

        jmArquivo.setText("Arquivo");

        jmiAbrir.setText("Abrir foto");
        jmiAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAbrirActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiAbrir);

        jmPrincipal.add(jmArquivo);

        setJMenuBar(jmPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlImage, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpopcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbexecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpopcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbexecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbexecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexecutarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbexecutarActionPerformed

    private void jsmascaraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsmascaraStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jsmascaraStateChanged

    private void jmiAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAbrirActionPerformed
        
    }//GEN-LAST:event_jmiAbrirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbexecutar;
    private javax.swing.JButton jbsalvar;
    private javax.swing.JLabel jlImage;
    private javax.swing.JLabel jlequalizacao;
    private javax.swing.JLabel jllimiar;
    private javax.swing.JLabel jllimiarizacao;
    private javax.swing.JLabel jllimiarutilizado;
    private javax.swing.JLabel jlopcoes;
    private javax.swing.JLabel jlpadraolimiar;
    private javax.swing.JLabel jlsegmentacao;
    private javax.swing.JLabel jlsuavizacao;
    private javax.swing.JLabel jltammask;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenuBar jmPrincipal;
    private javax.swing.JMenuItem jmiAbrir;
    private javax.swing.JPanel jpequalizacao;
    private javax.swing.JPanel jplimiarizacao;
    private javax.swing.JPanel jpopcoes;
    private javax.swing.JPanel jpsegmentacao;
    private javax.swing.JPanel jpsuavizacao;
    private javax.swing.JRadioButton jrequalizargb;
    private javax.swing.JRadioButton jrmaxentropia;
    private javax.swing.JRadioButton jrmediana;
    private javax.swing.JRadioButton jrpassabaixas;
    private javax.swing.JRadioButton jrprewitt;
    private javax.swing.JRadioButton jrroberts;
    private javax.swing.JRadioButton jrsobel;
    private javax.swing.JSlider jsmascara;
    // End of variables declaration//GEN-END:variables

    public JButton getJbexecutar() {
        return jbexecutar;
    }

    public void setJbexecutar(JButton jbexecutar) {
        this.jbexecutar = jbexecutar;
    }

    public JButton getJbsalvar() {
        return jbsalvar;
    }

    public void setJbsalvar(JButton jbsalvar) {
        this.jbsalvar = jbsalvar;
    }

    public JLabel getJlImage() {
        return jlImage;
    }

    public void setJlImage(JLabel jlImage) {
        this.jlImage = jlImage;
    }

    public JLabel getJlequalizacao() {
        return jlequalizacao;
    }

    public void setJlequalizacao(JLabel jlequalizacao) {
        this.jlequalizacao = jlequalizacao;
    }

    public JLabel getJllimiar() {
        return jllimiar;
    }

    public void setJllimiar(JLabel jllimiar) {
        this.jllimiar = jllimiar;
    }

    public JLabel getJllimiarizacao() {
        return jllimiarizacao;
    }

    public void setJllimiarizacao(JLabel jllimiarizacao) {
        this.jllimiarizacao = jllimiarizacao;
    }

    public JLabel getJllimiarutilizado() {
        return jllimiarutilizado;
    }

    public void setJllimiarutilizado(JLabel jllimiarutilizado) {
        this.jllimiarutilizado = jllimiarutilizado;
    }

    public JLabel getJlopcoes() {
        return jlopcoes;
    }

    public void setJlopcoes(JLabel jlopcoes) {
        this.jlopcoes = jlopcoes;
    }

    public JLabel getJlpadraolimiar() {
        return jlpadraolimiar;
    }

    public void setJlpadraolimiar(JLabel jlpadraolimiar) {
        this.jlpadraolimiar = jlpadraolimiar;
    }

    public JLabel getJlsegmentacao() {
        return jlsegmentacao;
    }

    public void setJlsegmentacao(JLabel jlsegmentacao) {
        this.jlsegmentacao = jlsegmentacao;
    }

    public JLabel getJlsuavizacao() {
        return jlsuavizacao;
    }

    public void setJlsuavizacao(JLabel jlsuavizacao) {
        this.jlsuavizacao = jlsuavizacao;
    }

    public JLabel getJltammask() {
        return jltammask;
    }

    public void setJltammask(JLabel jltammask) {
        this.jltammask = jltammask;
    }

    public JMenu getJmArquivo() {
        return jmArquivo;
    }

    public void setJmArquivo(JMenu jmArquivo) {
        this.jmArquivo = jmArquivo;
    }

    public JMenuBar getJmPrincipal() {
        return jmPrincipal;
    }

    public void setJmPrincipal(JMenuBar jmPrincipal) {
        this.jmPrincipal = jmPrincipal;
    }

    public JMenuItem getJmiAbrir() {
        return jmiAbrir;
    }

    public void setJmiAbrir(JMenuItem jmiAbrir) {
        this.jmiAbrir = jmiAbrir;
    }

    public JPanel getJpequalizacao() {
        return jpequalizacao;
    }

    public void setJpequalizacao(JPanel jpequalizacao) {
        this.jpequalizacao = jpequalizacao;
    }

    public JPanel getJplimiarizacao() {
        return jplimiarizacao;
    }

    public void setJplimiarizacao(JPanel jplimiarizacao) {
        this.jplimiarizacao = jplimiarizacao;
    }

    public JPanel getJpopcoes() {
        return jpopcoes;
    }

    public void setJpopcoes(JPanel jpopcoes) {
        this.jpopcoes = jpopcoes;
    }

    public JPanel getJpsegmentacao() {
        return jpsegmentacao;
    }

    public void setJpsegmentacao(JPanel jpsegmentacao) {
        this.jpsegmentacao = jpsegmentacao;
    }

    public JPanel getJpsuavizacao() {
        return jpsuavizacao;
    }

    public void setJpsuavizacao(JPanel jpsuavizacao) {
        this.jpsuavizacao = jpsuavizacao;
    }

    public JRadioButton getJrequalizargb() {
        return jrequalizargb;
    }

    public void setJrequalizargb(JRadioButton jrequalizargb) {
        this.jrequalizargb = jrequalizargb;
    }

    public JRadioButton getJrmaxentropia() {
        return jrmaxentropia;
    }

    public void setJrmaxentropia(JRadioButton jrmaxentropia) {
        this.jrmaxentropia = jrmaxentropia;
    }

    public JRadioButton getJrmediana() {
        return jrmediana;
    }

    public void setJrmediana(JRadioButton jrmediana) {
        this.jrmediana = jrmediana;
    }

    public JRadioButton getJrpassabaixas() {
        return jrpassabaixas;
    }

    public void setJrpassabaixas(JRadioButton jrpassabaixas) {
        this.jrpassabaixas = jrpassabaixas;
    }

    public JRadioButton getJrprewitt() {
        return jrprewitt;
    }

    public void setJrprewitt(JRadioButton jrprewitt) {
        this.jrprewitt = jrprewitt;
    }

    public JRadioButton getJrroberts() {
        return jrroberts;
    }

    public void setJrroberts(JRadioButton jrroberts) {
        this.jrroberts = jrroberts;
    }

    public JRadioButton getJrsobel() {
        return jrsobel;
    }

    public void setJrsobel(JRadioButton jrsobel) {
        this.jrsobel = jrsobel;
    }

    public JSlider getJsmascara() {
        return jsmascara;
    }

    public void setJsmascara(JSlider jsmascara) {
        this.jsmascara = jsmascara;
    }
}
