/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.recognition;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author anderson
 */
public class ViewPatternGeneration extends javax.swing.JFrame {

    /**
     * Creates new form ViewPatternGeneration
     */
    public ViewPatternGeneration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPattern = new javax.swing.JLabel();
        btnLocale = new javax.swing.JButton();
        lblPath = new javax.swing.JLabel();
        txtPath = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        pgBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPattern.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPattern.setText("Pattern Generation:");

        btnLocale.setText("Locale Data-base");

        lblPath.setText("Path:");

        txtPath.setText("...");

        btnStart.setText("Start");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLocale, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPattern)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPath)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPath)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pgBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPattern)
                .addGap(18, 18, 18)
                .addComponent(btnLocale)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPath)
                    .addComponent(txtPath))
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pgBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocale;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblPath;
    private javax.swing.JLabel lblPattern;
    private javax.swing.JProgressBar pgBar;
    private javax.swing.JLabel txtPath;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnLocale() {
        return btnLocale;
    }

    public void setBtnLocale(javax.swing.JButton btnLocale) {
        this.btnLocale = btnLocale;
    }

    public javax.swing.JButton getBtnStart() {
        return btnStart;
    }

    public void setBtnStart(javax.swing.JButton btnStart) {
        this.btnStart = btnStart;
    }

    public javax.swing.JProgressBar getPgBar() {
        return pgBar;
    }

    public void setPgBar(javax.swing.JProgressBar pgBar) {
        this.pgBar = pgBar;
    }

    public javax.swing.JLabel getTxtPath() {
        return txtPath;
    }

    public void setTxtPath(javax.swing.JLabel txtPath) {
        this.txtPath = txtPath;
    }
}
