/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.recognition;

/**
 *
 * @author anderson
 */
public class ViewSpeciesClassificationMultiple extends javax.swing.JFrame {

    /**
     * Creates new form ViewSpeciesClassificationMultiple
     */
    public ViewSpeciesClassificationMultiple() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnLocaleData = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPathData = new javax.swing.JLabel();
        btnLocalePattern = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPathPattern = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        rbEuclidiana = new javax.swing.JRadioButton();
        rbManhattan = new javax.swing.JRadioButton();
        pgBar = new javax.swing.JProgressBar();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Species Classification");

        btnLocaleData.setText("Locale Data-base");

        jLabel3.setText("Path data-base:");

        txtPathData.setText("...");

        btnLocalePattern.setText("Locale Pattern");

        jLabel5.setText("Path pattern:");

        txtPathPattern.setText("...");

        btnStart.setText("Start");

        jLabel7.setText("Distance:");

        rbEuclidiana.setText("Euclidiana");

        rbManhattan.setText("Manhattan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLocaleData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLocalePattern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pgBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(txtPathData)
                            .addComponent(jLabel5)
                            .addComponent(txtPathPattern)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(46, 46, 46)
                                .addComponent(rbEuclidiana)
                                .addGap(47, 47, 47)
                                .addComponent(rbManhattan)))
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLocaleData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPathData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLocalePattern)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPathPattern)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbEuclidiana)
                    .addComponent(rbManhattan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStart)
                .addGap(11, 11, 11)
                .addComponent(pgBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocaleData;
    private javax.swing.JButton btnLocalePattern;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JProgressBar pgBar;
    private javax.swing.JRadioButton rbEuclidiana;
    private javax.swing.JRadioButton rbManhattan;
    private javax.swing.JLabel txtPathData;
    private javax.swing.JLabel txtPathPattern;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnLocaleData() {
        return btnLocaleData;
    }

    public void setBtnLocalData(javax.swing.JButton btnLocaleData) {
        this.btnLocaleData = btnLocaleData;
    }

    public javax.swing.JButton getBtnLocalePattern() {
        return btnLocalePattern;
    }

    public void setBtnLocalePattern(javax.swing.JButton btnLocalePattern) {
        this.btnLocalePattern = btnLocalePattern;
    }

    public javax.swing.JButton getBtnStart() {
        return btnStart;
    }

    public void setBtnStart(javax.swing.JButton btnStart) {
        this.btnStart = btnStart;
    }

    public javax.swing.JProgressBar getPgBar() {
        return pgBar;
    }

    public void setPgBar(javax.swing.JProgressBar pgBar) {
        this.pgBar = pgBar;
    }

    public javax.swing.JRadioButton getRbEuclidiana() {
        return rbEuclidiana;
    }

    public void setRbEuclidiana(javax.swing.JRadioButton rbEuclidiana) {
        this.rbEuclidiana = rbEuclidiana;
    }

    public javax.swing.JRadioButton getRbManhattan() {
        return rbManhattan;
    }

    public void setRbManhattan(javax.swing.JRadioButton rbManhattan) {
        this.rbManhattan = rbManhattan;
    }

    public javax.swing.JLabel getTxtPathData() {
        return txtPathData;
    }

    public void setTxtPathData(javax.swing.JLabel txtPathData) {
        this.txtPathData = txtPathData;
    }

    public javax.swing.JLabel getTxtPathPattern() {
        return txtPathPattern;
    }

    public void setTxtPathPattern(javax.swing.JLabel txtPathPattern) {
        this.txtPathPattern = txtPathPattern;
    }
    

}
