/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.curvature;

import model.components.JImageView;

/**
 *
 * @author Anderson
 */
public class ViewFourier extends javax.swing.JFrame {

    /**
     * Creates new form ViewFourier
     */
    public ViewFourier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ImageViewRecorte = new JImageView();
        ImageView = new JImageView();
        jLabel4 = new javax.swing.JLabel();
        cbInitialPoint = new javax.swing.JCheckBox();
        cbRotation = new javax.swing.JCheckBox();
        cbTranslation = new javax.swing.JCheckBox();
        cbScala = new javax.swing.JCheckBox();
        btnGenerate = new javax.swing.JButton();
        lblComplex = new javax.swing.JLabel();
        ImageViewGrafico = new JImageView();
        jLabel2 = new javax.swing.JLabel();
        txtNumberCoefficients = new javax.swing.JTextField();
        pgBar = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fourier");

        ImageViewRecorte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout ImageViewRecorteLayout = new javax.swing.GroupLayout(ImageViewRecorte);
        ImageViewRecorte.setLayout(ImageViewRecorteLayout);
        ImageViewRecorteLayout.setHorizontalGroup(
            ImageViewRecorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        ImageViewRecorteLayout.setVerticalGroup(
            ImageViewRecorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ImageView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout ImageViewLayout = new javax.swing.GroupLayout(ImageView);
        ImageView.setLayout(ImageViewLayout);
        ImageViewLayout.setHorizontalGroup(
            ImageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        ImageViewLayout.setVerticalGroup(
            ImageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setText("Options invariants");

        cbInitialPoint.setText("Initial Point");

        cbRotation.setText("Rotation");

        cbTranslation.setText("Translation");

        cbScala.setText("Scala");

        btnGenerate.setText("Generate Curvature");

        lblComplex.setText("Complex coordinates");

        ImageViewGrafico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout ImageViewGraficoLayout = new javax.swing.GroupLayout(ImageViewGrafico);
        ImageViewGrafico.setLayout(ImageViewGraficoLayout);
        ImageViewGraficoLayout.setHorizontalGroup(
            ImageViewGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        ImageViewGraficoLayout.setVerticalGroup(
            ImageViewGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );

        jLabel2.setText("Number of coefficients");

        txtNumberCoefficients.setText("126");

        pgBar.setName(""); // NOI18N

        jLabel9.setBackground(new java.awt.Color(0, 255, 0));
        jLabel9.setOpaque(true);

        jLabel10.setText("Border");

        jLabel3.setText("legend:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(422, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumberCoefficients, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblComplex)
                        .addComponent(ImageViewGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ImageView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addComponent(ImageViewRecorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbTranslation)
                                        .addComponent(cbRotation)
                                        .addComponent(cbScala)
                                        .addComponent(cbInitialPoint)))
                                .addComponent(jLabel4)
                                .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumberCoefficients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(210, 210, 210))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(31, 31, 31)
                            .addComponent(cbInitialPoint)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbRotation)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbTranslation)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbScala)
                            .addGap(84, 84, 84)
                            .addComponent(btnGenerate))
                        .addComponent(ImageViewRecorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ImageView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(36, 36, 36)
                    .addComponent(lblComplex)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImageViewGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXImageView ImageView;
    private org.jdesktop.swingx.JXImageView ImageViewGrafico;
    private org.jdesktop.swingx.JXImageView ImageViewRecorte;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JCheckBox cbInitialPoint;
    private javax.swing.JCheckBox cbRotation;
    private javax.swing.JCheckBox cbScala;
    private javax.swing.JCheckBox cbTranslation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblComplex;
    private javax.swing.JProgressBar pgBar;
    private javax.swing.JTextField txtNumberCoefficients;
    // End of variables declaration//GEN-END:variables

    public JImageView getImageView() {
        return (JImageView) ImageView;
    }

    public void setImageView(org.jdesktop.swingx.JXImageView ImageView) {
        this.ImageView = ImageView;
    }

    public JImageView getImageViewGrafico() {
        return (JImageView) ImageViewGrafico;
    }

    public void setImageViewGrafico(org.jdesktop.swingx.JXImageView ImageViewGrafico) {
        this.ImageViewGrafico = ImageViewGrafico;
    }

    public JImageView getImageViewRecorte() {
        return (JImageView) ImageViewRecorte;
    }

    public void setImageViewRecorte(org.jdesktop.swingx.JXImageView ImageViewRecorte) {
        this.ImageViewRecorte = ImageViewRecorte;
    }

    public javax.swing.JButton getBtnGenerate() {
        return btnGenerate;
    }

    public void setBtnGenerate(javax.swing.JButton btnGenerate) {
        this.btnGenerate = btnGenerate;
    }

    public javax.swing.JCheckBox getCbInitialPoint() {
        return cbInitialPoint;
    }

    public void setCbInitialPoint(javax.swing.JCheckBox cbInitialPoint) {
        this.cbInitialPoint = cbInitialPoint;
    }

    public javax.swing.JCheckBox getCbRotation() {
        return cbRotation;
    }

    public void setCbRotation(javax.swing.JCheckBox cbRotation) {
        this.cbRotation = cbRotation;
    }

    public javax.swing.JCheckBox getCbScala() {
        return cbScala;
    }

    public void setCbScala(javax.swing.JCheckBox cbScala) {
        this.cbScala = cbScala;
    }

    public javax.swing.JCheckBox getCbTranslation() {
        return cbTranslation;
    }

    public void setCbTranslation(javax.swing.JCheckBox cbTranslation) {
        this.cbTranslation = cbTranslation;
    }

    public javax.swing.JTextField getTxtNumberCoefficients() {
        return txtNumberCoefficients;
    }

    public void setTxtNumberCoefficients(javax.swing.JTextField txtNumberCoefficients) {
        this.txtNumberCoefficients = txtNumberCoefficients;
    }

    public javax.swing.JProgressBar getPgBar() {
        return pgBar;
    }

    public void setPgBar(javax.swing.JProgressBar pgBar) {
        this.pgBar = pgBar;
    }
    
    
}
